export { EXTERNAL_LINKS } from './links';
export { THEME } from './theme';
export {
  BASE_MVP_PRICE_USD,
  BOOK_CALL_CTA,
  BOOK_CALL_SHORT_CTA,
  BRAND_NAME,
  CALL_DURATION_MINUTES,
  DEVELOPMENT_HOURS,
  DISCOVERY_HOURS,
  FIXED_PRICE_NO_SURPRISES,
  FIXED_PRICE_SHORT,
  GET_FREE_ESTIMATE_CTA,
  MVP_DELIVERY_HOURS,
  RESPONSE_TIME_HOURS,
  SITE_URL,
  SUPPORT_DAYS,
} from './business';
